### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by xu1998hz** [OpenBMB/Eurus#13]
I have a quick question regarding to the training data of Eurus. Do you directly use instruction as input and response as output shown in HF (openbmb/UltraInteract_sft) or you have some other formatting strategies. Because I found prompts in evaluation code is quite different from training data.

**Comment by lifan-yuan** [comment]
Hi,

yes, we directly trained models with the prompt format as shown in HF. The prompt in training data and eval code should be the same for math. However, for coding, we modified the eval prompt based on [Qwen repo](https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_chat_humaneval.py) because the output formats greatly affected eval results. Thus more specific instructions are needed for correctly formatted responses.

**Comment by xu1998hz** [comment]
Thanks a lot for your prompt response!
